### ISSUE TITLE
Why were js/css cache-busting querystrings removed in 5.6.3?

### ISSUE THREAD

**Issue by jordanlev** [concretecms/concrete5-legacy#1924]
This change: https://github.com/concrete5/concrete5-legacy/commit/7547f3ab3ea794838b344b4d51c3be2c2d683bca#diff-c428d44ba35650c74dfe9b032e51a419L133
...removed the "?v=..." querystring args from css and js files (which served the useful purpose of forcing a browser reload of css/js files that have been changed).

I'm curious what the reason for this is, because we have been bitten by its removal (without realizing it was removed). Was it just a philosophical decision about how these things should be handled (e.g. the CMS shouldn't be responsible for it but rather it should be handled by grunt/gulp/etc, or the problems it causes for some proxy servers)? Or was it a technical issue? In other words, could I add back these 4 lines from the html helper file in 5.6.3 to restore this functionality? Or is it tied to some other change that will break things?

Thanks!

**Comment by JohntheFish** [comment]
+1

**Comment by Remo** [comment]
@aembler do you remember why you've removed this line?

**Comment by aembler** [comment]
Honestly, I think we removed it because the way we computed it it employed the password salt – so on some older sites (or sites upgraded from older sites) you could use that string to brute force the password salt back. Making that string built off of password salt was a crazy stupid decision in the first place. You could probably add it back just md5ing it off of the version constant and it would be fine.

**Comment by Remo** [comment]
That makes sense, thanks Andrew!

Remo Laubacher | remo.laubacher@gmail.com
Dorfplatz 11 | 6052 Hergiswil | Switzerland
Mobile 0041 78 820 07 57 | Skype: remo.laubacher

**Comment by JohntheFish** [comment]
Could it simply be the file timestamp? Cheap to process. Guaranteed to evolve when the file is written,

**Comment by Remo** [comment]
File operations aren't that cheap, the salt was certainly cheaper, but I agree that we shouldn't use salt for that.

**Comment by JohntheFish** [comment]
Yes, see what you mean. I was thinking of greater differentiation than just the c5 app version. Differentiation by file would be a useful enhancement for general css/js development.

**Comment by Remo** [comment]
Yeah that's a valid point. I'd personally consider the benefit good enough to use `filemtime` here. @jordanlev do you have an opinion about this?

**Comment by JohntheFish** [comment]
Maybe a version string could be an optional parameter to the html helper, in the array that Jordan added way back. That way developers could inject whatever they wanted, such as the package version (which I am guessing is cheaper to get from within a package than a timestamp).

**Comment by JohntheFish** [comment]
Meaning not the resource version that is already implemented.

**Comment by Remo** [comment]
I'm a bit hesitant about such changes for 5.6, existing devs won't learn about it and new devs won't use it because they are focusing on 5.7. It's probably not worth the effort, I mostly care about the functionality we've had in the first place as this is something that's kind of broken now.

**Comment by JohntheFish** [comment]
I could have used it over the last couple of months on a couple of fiddly 5.6 update projects with a lot of css tweaking.
Suppose the logic was additional parameter from developer or default to the app version made url compatible. That way the old functionality is restored, we can actually read what is loading from the dev console, and those who want have that little bit extra.

**Comment by Remo** [comment]
you can always override the helper.. I seriously doubt that more than a handful devs would actually use this. My main goal is to fix what got broken.

**Comment by jordanlev** [comment]
Hey guys,
I agree with Remo that adding new features is a very narrow use-case and probably not appropriate for the 5.6.x "legacy" branch.

In terms of returning old functionality... I'm not actually sure how it worked exactly: Was it supposed to change for every request? Or only change when the file was changed? And would the behaviour be different if the site were in "debug mode" vs. "production mode"?

Seems to me that either a file checksum or a datestamp check would be the only possible way to change it when the file changes, so whichever is quicker would be my vote (which sounds like it would be the `filemtime` function). Surely checking the timestamp on less than a dozen files for each request is a drop in the bucket compared to the number of actual php files that need to be read through the course of a usual page request?

**Comment by aembler** [comment]
It was dumber than that. It was only supposed to change when the version of concrete5 changed. 

This was really meant to just guard against core file caching, people updating, and then griping that editing was broken – when in actuality they just need to clear their browser cache. It really wasn't ever meant as a userland theme-specific solution. 

Which is why md5-ing the APP_VERSION constant would be enough to restore the previous behavior, sans the security hole.

**Comment by JohntheFish** [comment]
Why is it an advantage to MD5 the APP_VERSION? Is there any reason it couldn't be escaped and appended in a readable form?

**Comment by aembler** [comment]
Some people don't want to advertise which version they're running.
Obviously, there are ways to figure it out if you know what to look for,
but some obfuscation is probably not a bad thing.
