### ISSUE TITLE
Any way to replace swfupload for multiple uploads?

### ISSUE THREAD

**Issue by pripboy** [concretecms/concrete5-legacy#2004]
Chrome warns that flash is discontinued in December 2020. There's any alternative to swfupload?

**Comment by hissy** [comment]
modern concrete5 already replaced to Javascript based file upload. Please use it. https://github.com/concrete5/concrete5

**Comment by pripboy** [comment]
> modern concrete5 already replaced to Javascript based file upload. Please use it. https://github.com/concrete5/concrete5

Thanks hissy, but I already know that. The question was for concrete5 legacy

**Comment by JohntheFish** [comment]
My Front End uploader provides a solution for this. Pop-up multi file uploader. Tested on php7.4 and c5.6.4.0. No need for Flash.
https://www.concrete5.org/marketplace/addons/front-end-file-uploader/
Legacy marketplace is closed. You can purchase through a special offer https://www.concrete5.org/offers/-/jpt45zglr9ki/

**Comment by ConcreteOwl** [comment]
Hutman has created a free replacement for the swf-uploader.
You can download a copy at https://github.com/hutman/c56dropzone
Just follow the instructions exactly and it will work very nicely.

**Comment by prpdesigns** [comment]
> Hutman has created a free replacement for the swf-uploader. You can download a copy at https://github.com/hutman/c56dropzone Just follow the instructions exactly and it will work very nicely.

Works flawlessly. Thanks!
