### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by brandymedia** [concretecms/concrete5-legacy#2009]
Are there any plans to support PHP 8 in the future?

**Comment by Remo** [comment]
Getting it working with PHP 7 was quite a big chunk of work. You can see most changes in this pull request https://github.com/concretecms/concrete5-legacy/pull/1955

I would assume that PHP 8 should be easier as we had a few quirks in the codebase before, but they were improved with that pull request, but that's nothing more than a gut feeling.

**Comment by brandymedia** [comment]
Thanks for the info, I’ll check out the PR and try and gauge what work was
involved.

I don’t think there are loads of breaking changes between PHP 7 and PHP 8
but no doubt there will be a lot of work to do across such a big codebase.

Thanks again 👍

**Comment by ConcreteOwl** [comment]
Many php fatal errors were suppressed in the 5.6.4.0 codebase using the '@' symbol.
php 7 allowed the errors to be silenced when prepended by the @ symbol.
php 8 does not allow the suppresion of these errors.
Read this article for a full explanation, https://php.watch/versions/8.0/fatal-error-suppression

**Comment by Remo** [comment]
@ConcreteOwl yes, that's a good point. We did remove some of the `@`'s, but there are still plenty left. This could indeed by a main cause for headaches. I guess one would have to remove them and start praying or more likely, start fixing.

**Comment by brandymedia** [comment]
That’s good to know, thanks David.

I’d have to check the codebase to see how common these are but from what
you’ve said, I’d imagine there are quite a few.

This obviously could present a massive headache  when looking to get this
working with PHP 8 and beyond.

**Comment by ConcreteOwl** [comment]
@brandymedia (Andy)
Yes a major headache for anyone wanting to update 5.6.4.0 to run on PHP 8.
I have come to the conclusion your time is better spent finding a good hosting company that is going to continue supporting PHP 7.
If you do try to update the codebase, please keep us informed of your progress.
Best Regards
David

**Comment by JohntheFish** [comment]
Its not just the core code. Its all the 3rd party code pulled in to the core. Then all the themes/addons/application code.  You would also need to update these for php8 compatibility or to suppress the errors.

**Comment by ktarasov** [comment]
We tried to run code 5.6.4 on PHP 8, ran into problems in AdoDB. But we will slowly do this with an incomprehensible perspective.

**Comment by ConcreteOwl** [comment]
@ktarasov if you make any progress with this I would love to hear from you, I too have failed with the AdoDB errors and have not yet found a solution, although I have not spent a lot of time trying.
Good Luck
